name: generate_readme_with_stats
on:
  schedule:
    - cron: '0 */24 * * *'
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate stats on README.md
      uses: teoxoy/profile-readme-stats@v2
      with:
        token: ${{ secrets.ACTIONS }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add .
        git commit -m "Update README"
        git push
        fi
